#!/usr/bin/env python3
"""The docs' structure: sections, the contents page and previous/next links.

    docs_sections.py sync    write docs/README.md and every page's previous/next links
    docs_sections.py check   fail if a page has no valid section, or either is out of date

docs/sections.json lists the sections in order. Each page in docs/ names its section and its
place in it in its front matter:

    section: build-reports
    position: 3

From these this script writes docs/README.md (the contents page GitHub shows for docs/) and a
"Previous / Next" line at the end of every page, after a `<!-- docs-nav -->` marker. getdre.com
builds its sidebar from the same file, so the order matches everywhere. Generators that rewrite a
page (schema_docs.py, the error codes and CLI reference tests) keep what follows the marker.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
MARKER = "<!-- docs-nav: generated by .github/scripts/docs_sections.py from docs/sections.json -->"


def strip_nav(text):
    """The page without its previous/next block."""
    i = text.find("\n<!-- docs-nav")
    return text if i < 0 else text[: i + 1]


def front_matter(text):
    """The page's front matter as `key: value` lines (top level only), or None."""
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if not m:
        return None
    fields = {}
    for line in m.group(1).splitlines():
        km = re.match(r"([A-Za-z_]+):\s*(.*)$", line)
        if km:
            fields[km.group(1)] = km.group(2).strip()
    return fields


def unquote(v):
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
        return json.loads(v) if v[0] == '"' else v[1:-1]
    return v


def load(docs=DOCS):
    """The sections, each with its pages in order, and every problem found."""
    sections = json.loads((docs / "sections.json").read_text())["sections"]
    ids = [s["id"] for s in sections]
    pages = {s["id"]: [] for s in sections}
    errors = []
    for path in sorted(docs.glob("*.md")):
        if path.name == "README.md":
            continue
        fm = front_matter(path.read_text())
        name = path.stem
        if fm is None:
            errors.append(f"docs/{path.name}: no front matter")
            continue
        if "sidebar" in fm:
            errors.append(f"docs/{path.name}: `sidebar:` is replaced by `section:` and `position:`")
        section = fm.get("section")
        if section not in pages:
            errors.append(
                f"docs/{path.name}: `section:` must be one of {', '.join(ids)}"
                + (f", got `{section}`" if section else "")
            )
            continue
        try:
            position = int(fm.get("position", ""))
        except ValueError:
            errors.append(f"docs/{path.name}: `position:` must be a whole number (its place in `{section}`)")
            continue
        for k in ("title", "description"):
            if not fm.get(k):
                errors.append(f"docs/{path.name}: no `{k}:`")
        pages[section].append((position, name, unquote(fm.get("title", name)), unquote(fm.get("description", ""))))
    for s in sections:
        seen = {}
        for position, name, _, _ in pages[s["id"]]:
            if position in seen:
                errors.append(f"docs/{name}.md and docs/{seen[position]}.md both have position {position} in `{s['id']}`")
            seen[position] = name
        pages[s["id"]].sort()
    return sections, pages, errors


def order(sections, pages):
    """Every page, in reading order: (name, title)."""
    return [(name, title) for s in sections for _, name, title, _ in pages[s["id"]]]


def nav(prev, nxt):
    parts = []
    if prev:
        parts.append(f"**Previous:** [{prev[1]}]({prev[0]}.md)")
    if nxt:
        parts.append(f"**Next:** [{nxt[1]}]({nxt[0]}.md)")
    return f"{MARKER}\n\n---\n\n{' · '.join(parts)}\n"


def with_nav(text, prev, nxt):
    return strip_nav(text).rstrip("\n") + "\n\n" + nav(prev, nxt)


def readme(sections, pages):
    lines = [
        "# DRE documentation",
        "",
        "<!-- Generated by .github/scripts/docs_sections.py from docs/sections.json and each page's front matter. -->",
        "",
        "The same pages, in the same order, are on [getdre.com/docs](https://getdre.com/docs/).",
        "",
    ]
    for s in sections:
        lines += [f"## {s['title']}", "", s["description"], ""]
        for _, name, title, description in pages[s["id"]]:
            lines.append(f"- [{title}]({name}.md): {description}")
        lines.append("")
    lines += [
        "## Adding a page",
        "",
        "Give the page a `title`, a one-line `description`, its `section` (an `id` from",
        "[`sections.json`](sections.json)) and its `position` in that section, in its front matter. Then run",
        "`python3 .github/scripts/docs_sections.py sync` to update this page and the previous/next links.",
        "CI checks both.",
        "",
    ]
    return "\n".join(lines)


def expected(docs=DOCS):
    """What every file should hold: {path: text}, and the problems found."""
    sections, pages, errors = load(docs)
    if errors:
        return {}, errors
    files = {docs / "README.md": readme(sections, pages)}
    seq = order(sections, pages)
    for i, (name, _) in enumerate(seq):
        path = docs / f"{name}.md"
        prev = seq[i - 1] if i > 0 else None
        nxt = seq[i + 1] if i + 1 < len(seq) else None
        files[path] = with_nav(path.read_text(), prev, nxt)
    return files, []


def main(argv):
    cmd = argv[1] if len(argv) > 1 else "check"
    files, errors = expected()
    if errors:
        print("docs/ structure problems:", *errors, sep="\n  ")
        return 1
    stale = [p for p, text in files.items() if not p.is_file() or p.read_text() != text]
    if cmd == "sync":
        for p in stale:
            p.write_text(files[p])
        print(f"updated {len(stale)} file(s)")
        return 0
    if stale:
        print(
            "out of date; run `python3 .github/scripts/docs_sections.py sync`:",
            *(str(p.relative_to(ROOT)) for p in stale),
            sep="\n  ",
        )
        return 1
    print("docs/README.md and the previous/next links are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
