#!/usr/bin/env python3
"""The first-party plugin pages, docs/plugin-<page>.md: their generated part.

    plugin_pages.py sync    rewrite each page's generated block
    plugin_pages.py check   fail if a block is out of date or a page is missing

Each page starts, under its title, with a block generated from the plugin package's
describe.json (itself checked against the built plugins in CI) and .github/scripts/packages.json:
what the plugin is, how to install it, and a table of its profile fields and options. The prose
after the block is written by hand. The block sits between the markers below; sync replaces only
what's between them.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
PACKAGES = json.loads((ROOT / ".github/scripts/packages.json").read_text())
BEGIN = "<!-- BEGIN generated by .github/scripts/plugin_pages.py from the package's describe.json -->"
END = "<!-- END generated -->"

# Each page: its plugins, in order. A page holds one plugin, or a few that share their docs.
PAGES = {
    "duckdb": ["source/duckdb"],
    "postgres": ["source/postgres"],
    "databricks": ["source/databricks", "destination/databricks"],
    "bigquery": ["source/bigquery"],
    "snowflake": ["source/snowflake"],
    "csv": ["format/csv", "format/delimited"],
    "fixed_width": ["format/fixed_width"],
    "parquet": ["format/parquet"],
    "xlsx": ["format/xlsx"],
    "s3": ["destination/s3"],
    "gcs": ["destination/gcs"],
    "azure_blob": ["destination/azure_blob"],
    "sftp": ["destination/sftp"],
    "ftp": ["destination/ftp"],
    "email": ["destination/email"],
    "slack": ["destination/slack"],
    "teams": ["destination/teams"],
    "google_chat": ["destination/google_chat"],
}


def page_path(page):
    return DOCS / f"plugin-{page}.md"


def package_of(plugin):
    return next(p for p, about in PACKAGES.items() if plugin in about["provides"])


def describe(plugin):
    about = PACKAGES[package_of(plugin)]
    path = ROOT / about.get("go", f"plugins/{package_of(plugin)}") / "describe.json"
    return json.loads(path.read_text())[plugin]


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def shown(v):
    """A value as code: strings as written, unless empty or holding a control character (`"\\r\\n"`)."""
    if v is None:
        return ""
    plain = isinstance(v, str) and v and not any(c < " " for c in v)
    return f"`{v if plain else json.dumps(v)}`"


def sentence(text):
    """`port` → `Port.`: a description as a sentence."""
    text = cell(text).strip()
    if not text:
        return ""
    text = text[0].upper() + text[1:]
    return text if text.endswith((".", ")", "`")) else text + "."


def field_notes(f):
    notes = [sentence(f.get("description", ""))]
    if f.get("choices"):
        notes.append("One of " + ", ".join(shown(c) for c in f["choices"]) + ".")
    kind = f.get("kind")
    if kind == "path":
        notes.append("A file path; `~/` is your home directory.")
    elif kind == "duration":
        notes.append("A duration (`30s`, `2m`) or seconds.")
    if f.get("secret"):
        notes.append("Secret: use `env_var()`.")
    return " ".join(n for n in notes if n)


def field_table(fields):
    rows = ["| Field | Default | Notes |", "|---|---|---|"]
    for f in fields:
        name = f"`{f['name']}`" + (" (required)" if f.get("required") else "")
        rows.append(f"| {name} | {shown(f.get('default'))} | {field_notes(f)} |")
    return "\n".join(rows)


def option_table(options):
    rows = ["| Option | Type | Default | Notes |", "|---|---|---|---|"]
    for o in options:
        notes = sentence(o.get("description", ""))
        if o.get("choices"):
            notes += " One of " + ", ".join(shown(c) for c in o["choices"]) + "."
        name = f"`{o['name']}`" + (" (required)" if o.get("required") else "")
        rows.append(f"| {name} | {o['type']} | {shown(o.get('default'))} | {notes} |")
    return "\n".join(rows)


def block(page):
    plugins = PAGES[page]
    package = package_of(plugins[0])
    names = " and ".join(f"`{p.split('/')[1]}` {p.split('/')[0]}" for p in plugins)
    out = [
        BEGIN,
        "",
        f"{PACKAGES[package]['description']}: the {names}, from the `{package}` package. Declare the "
        "package once in `dependencies.yml`; DRE installs it on demand:",
        "",
        "```yaml",
        "# dependencies.yml",
        "plugins:",
        f"  - {package}",
        "```",
    ]
    for plugin in plugins:
        kind, name = plugin.split("/")
        reply = describe(plugin)
        prefix = f"`{name}` {kind}: " if len(plugins) > 1 else ""
        if kind != "format":
            section = "connections" if kind == "source" else "destinations"
            out += ["", f"### {prefix}profile fields" if prefix else "### Profile fields", "",
                    f"Set in `profiles.yml`, under `{section}:`, in a target with `type: {name}`.", "",
                    field_table(reply["connection_fields"])]
        if reply.get("option_fields"):
            where = ("a report's `output:` (or `format_options.%s` in `dre_project.yml`)" % name
                     if kind == "format" else "the report's `output.destination` entry")
            out += ["", f"### {prefix}options" if prefix else "### Options", "", f"Set in {where}.", "",
                    option_table(reply["option_fields"])]
        elif kind == "format":
            out += ["", f"### {prefix}options" if prefix else "### Options", "", "None."]
    out += ["", END]
    return "\n".join(out)


def rewrite(text, page):
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0:
        raise SystemExit(f"{page_path(page)}: no generated block (add the markers under the title)")
    return text[:i] + block(page) + text[j + len(END):]


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd not in ("sync", "check"):
        raise SystemExit(__doc__)
    stale = []
    for page in PAGES:
        path = page_path(page)
        if not path.exists():
            stale.append(f"{path} is missing")
            continue
        text = path.read_text()
        new = rewrite(text, page)
        if new != text:
            if cmd == "sync":
                path.write_text(new)
            else:
                stale.append(f"{path} is out of date: run `python3 .github/scripts/plugin_pages.py sync`")
    for s in stale:
        print(s)
    if cmd == "check" and stale:
        sys.exit(1)
    if cmd == "sync" and any("missing" in s for s in stale):
        sys.exit(1)


if __name__ == "__main__":
    main()
