[package]
name = "dre-plugin-duckdb"
description = "DRE source plugin: DuckDB"
version = "1.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
dre-protocol.workspace = true
duckdb = { workspace = true, features = ["appender-arrow"] }
arrow = { workspace = true, features = ["ffi"] }
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
